export interface PresetTag {
  id: string;
  cn: string;
  en: string;
  prompt: string;
  desc?: string;
}

export interface TagCategory {
  key: string;
  cn: string;
  en: string;
  icon: string;
  tags: PresetTag[];
}

export interface ComboTemplate {
  id: string;
  cn: string;
  en: string;
  icon: string;
  desc: string;
  tagIds: string[];
}

export const TAG_LIBRARY: TagCategory[] = [
  /* ============ 1. 运镜 Motion ============ */
  {
    key: "motion",
    cn: "运镜",
    en: "Motion",
    icon: "🎥",
    tags: [
      { id: "pov", cn: "第一视角", en: "POV",
        prompt: "first-person POV shot, immersive perspective, eye-level subjective view",
        desc: "代入感强" },
      { id: "handheld", cn: "手持镜头", en: "Handheld",
        prompt: "handheld camera, slight shake, documentary feel, organic motion",
        desc: "纪录真实感" },
      { id: "tracking", cn: "跟拍镜头", en: "Tracking",
        prompt: "smooth tracking shot following the subject, side-tracking dolly movement",
        desc: "跟随主体" },
      { id: "dolly_zoom", cn: "变焦推拉", en: "Dolly Zoom",
        prompt: "dolly zoom effect, vertigo Hitchcock effect, background warping",
        desc: "希区柯克眩晕" },
      { id: "crane_up", cn: "升降镜头", en: "Crane Up",
        prompt: "crane up shot, rising camera revealing scene from below to above",
        desc: "升起揭示" },
      { id: "tilt_up", cn: "俯仰镜头", en: "Tilt Up",
        prompt: "tilt up camera, vertical pan from ground to sky",
        desc: "纵向摇摄" },
      { id: "pan", cn: "横向摇镜", en: "Pan",
        prompt: "horizontal panning shot, smooth left-to-right rotation",
        desc: "水平扫描" },
      { id: "crane_down", cn: "下降镜头", en: "Crane Down",
        prompt: "crane down shot, descending camera from high to eye-level",
        desc: "由高至低" },
      { id: "orbit", cn: "环绕镜头", en: "Orbit",
        prompt: "orbiting camera, 360 degree circular movement around subject",
        desc: "360 围绕" },
      { id: "crash_out", cn: "快速拉远", en: "Crash Zoom Out",
        prompt: "crash zoom out, rapid aggressive pullback, sudden reveal",
        desc: "突然拉远" },
      { id: "crash_in", cn: "快速推近", en: "Crash Zoom In",
        prompt: "crash zoom in, rapid aggressive push, dramatic emphasis",
        desc: "突然推近" },
      { id: "dolly_out", cn: "拉远镜头", en: "Dolly Out",
        prompt: "slow dolly out, smooth backward movement, gradual reveal",
        desc: "缓慢后退" },
      { id: "dolly_in", cn: "推进镜头", en: "Dolly In",
        prompt: "slow dolly in, smooth forward push, intimate approach",
        desc: "缓慢推近" },
    ],
  },

  /* ============ 2. 镜头语言 Shot Language ============ */
  {
    key: "shotlang",
    cn: "镜头语言",
    en: "Shot Language",
    icon: "🎞",
    tags: [
      { id: "push", cn: "推镜", en: "Push In",
        prompt: "push-in shot, slow forward motion focusing tighter on subject, increasing tension",
        desc: "由远及近,聚焦主体" },
      { id: "pull", cn: "拉镜", en: "Pull Out",
        prompt: "pull-out shot, slow backward motion revealing wider context, emotional release",
        desc: "由近及远,释放情绪" },
      { id: "swing", cn: "摇镜", en: "Swing/Sweep",
        prompt: "swing pan shot, smooth horizontal or vertical sweep across the scene, transition between subjects",
        desc: "扫过场景,转移注意" },
      { id: "trolley", cn: "移镜", en: "Trolley/Slide",
        prompt: "trolley sliding shot, lateral camera movement parallel to subject, smooth tracking",
        desc: "侧向平移" },
      { id: "follow", cn: "跟镜", en: "Follow",
        prompt: "follow shot from behind subject, third-person tracking, immersive companionship",
        desc: "背后跟随" },
      { id: "rise", cn: "升镜", en: "Boom Up",
        prompt: "boom up shot, vertical rise revealing more of the scene from above",
        desc: "垂直上升" },
      { id: "descent", cn: "降镜", en: "Boom Down",
        prompt: "boom down shot, vertical descent zooming into detail, focusing intimacy",
        desc: "垂直下降" },
      { id: "whip", cn: "甩镜", en: "Whip Pan",
        prompt: "whip pan, ultra-fast horizontal blur transition, kinetic energy",
        desc: "极速摇摄" },
      { id: "shake", cn: "晃镜", en: "Shaky Cam",
        prompt: "shaky handheld cam, intense camera shake, chaos and urgency",
        desc: "强烈晃动" },
      { id: "static", cn: "固定镜头", en: "Static",
        prompt: "static locked-off shot, completely still camera, contemplative composition",
        desc: "完全静止" },
      { id: "low_angle", cn: "仰拍", en: "Low Angle",
        prompt: "low angle shot, camera below eye level looking up, heroic powerful feeling",
        desc: "仰视,英雄感" },
      { id: "high_angle", cn: "俯拍", en: "High Angle",
        prompt: "high angle shot, camera above looking down, vulnerable diminished feeling",
        desc: "俯视,弱化感" },
      { id: "birds_eye", cn: "鸟瞰", en: "Bird's Eye",
        prompt: "bird's eye view, top-down aerial perspective, god-like overview",
        desc: "正上方俯视" },
      { id: "dutch", cn: "倾斜镜头", en: "Dutch Angle",
        prompt: "dutch angle, tilted canted frame, psychological unease and tension",
        desc: "荷兰角,不安感" },
    ],
  },

  /* ============ 3. 镜头 Lens ============ */
  {
    key: "lens",
    cn: "镜头",
    en: "Lens",
    icon: "🔭",
    tags: [
      { id: "8mm", cn: "8mm 超广角", en: "8mm Ultra-Wide",
        prompt: "shot on 8mm ultra-wide lens, extreme spatial distortion",
        desc: "极端畸变" },
      { id: "probe", cn: "Laowa 探针微距", en: "Probe Macro",
        prompt: "shot on Laowa 24mm Probe Macro, insect-eye view, deep focus",
        desc: "探入式微距" },
      { id: "fisheye", cn: "鱼眼", en: "Fisheye",
        prompt: "fisheye lens, extreme barrel distortion, 180-degree FOV",
        desc: "圆形畸变" },
      { id: "vintage", cn: "复古老镜头", en: "Vintage",
        prompt: "vintage lens look, soft optics, lens flare, dreamy bokeh",
        desc: "柔焦+耀光" },
      { id: "tilt_shift", cn: "移轴", en: "Tilt-Shift",
        prompt: "tilt-shift lens, miniature effect, selective focus plane",
        desc: "微缩模型" },
      { id: "anamorphic", cn: "变形宽银幕", en: "Anamorphic",
        prompt: "anamorphic lens, 2.39:1 widescreen, oval bokeh, blue lens flare",
        desc: "蓝色耀光" },
      { id: "macro", cn: "微距", en: "Macro",
        prompt: "macro lens, extreme detail, ultra shallow depth of field",
        desc: "极致细节" },
      { id: "200mm", cn: "200mm 超长焦", en: "200mm Telephoto",
        prompt: "shot on 200mm super telephoto, extreme spatial compression",
        desc: "压迫感" },
      { id: "135mm", cn: "135mm 长焦", en: "135mm",
        prompt: "shot on 135mm telephoto, spatial compression, beautiful bokeh",
        desc: "中长焦人像" },
      { id: "18mm", cn: "18mm 超广角", en: "18mm Ultra-Wide",
        prompt: "shot on 18mm ultra-wide, epic scale, expansive landscape",
        desc: "史诗广度" },
      { id: "24mm", cn: "24mm 广角", en: "24mm Wide",
        prompt: "shot on 24mm wide, spatial tension, environmental storytelling",
        desc: "环境叙事" },
      { id: "85mm", cn: "85mm 人像", en: "85mm Portrait",
        prompt: "shot on 85mm, cinematic portrait, creamy bokeh",
        desc: "电影人像" },
      { id: "50mm", cn: "50mm 标准", en: "50mm Standard",
        prompt: "shot on 50mm prime, natural human eye perspective",
        desc: "肉眼视角" },
      { id: "35mm_cine", cn: "35mm 电影", en: "35mm Cinema",
        prompt: "shot on 35mm cinema lens, natural storytelling perspective",
        desc: "电影叙事" },
    ],
  },

  /* ============ 4. 相机 Camera ============ */
  {
    key: "camera",
    cn: "相机",
    en: "Camera",
    icon: "📷",
    tags: [
      { id: "kodak_35", cn: "柯达 35mm 胶片", en: "Kodak 35mm",
        prompt: "shot on Kodak 35mm film, natural film grain, warm tones, halation",
        desc: "传统胶片" },
      { id: "leica_sl2", cn: "徕卡 SL2", en: "Leica SL2",
        prompt: "shot on Leica SL2, signature color science, microcontrast",
        desc: "徕卡德味" },
      { id: "fuji_gfx", cn: "富士 GFX100", en: "Fuji GFX100",
        prompt: "shot on Fujifilm GFX100, medium format depth, painterly skin",
        desc: "中画幅" },
      { id: "canon_r5c", cn: "佳能 R5C", en: "Canon R5C",
        prompt: "shot on Canon EOS R5C, digital sharpness, vibrant color",
        desc: "数码锐利" },
      { id: "canon_c500", cn: "佳能 C500 II", en: "Canon C500",
        prompt: "shot on Canon C500 Mark II, soft skin tones, Canon Log 3",
        desc: "柔和肤色" },
      { id: "panavision", cn: "Panavision DXL2", en: "Panavision",
        prompt: "shot on Panavision Millennium DXL2, Hollywood blockbuster look",
        desc: "好莱坞质感" },
      { id: "imax_70", cn: "IMAX 70mm", en: "IMAX 70mm",
        prompt: "shot on IMAX 70mm film, epic large-format image, immense depth",
        desc: "史诗画面" },
      { id: "sony_fx6", cn: "Sony FX6", en: "Sony FX6",
        prompt: "shot on Sony FX6, documentary handheld feel, S-Cinetone",
        desc: "纪录手持" },
      { id: "sony_venice", cn: "Sony Venice", en: "Sony Venice",
        prompt: "shot on Sony Venice, dual-base ISO, real documentary meets film",
        desc: "纪录+电影" },
      { id: "red_monstro", cn: "RED Monstro 8K", en: "RED Monstro",
        prompt: "shot on RED Monstro 8K VV, hybrid commercial-cinematic look",
        desc: "电影+广告" },
      { id: "red_raptor", cn: "RED V-Raptor 8K", en: "RED Raptor",
        prompt: "shot on RED V-Raptor 8K, razor-sharp commercial imagery",
        desc: "锐利商业" },
      { id: "alexa_mini", cn: "ARRI Alexa Mini LF", en: "Alexa Mini LF",
        prompt: "shot on ARRI Alexa Mini LF, signature ARRI skin tone",
        desc: "通用旗舰" },
      { id: "alexa_65", cn: "ARRI Alexa 65", en: "Alexa 65",
        prompt: "shot on ARRI Alexa 65, top-tier cinematic image, large format",
        desc: "顶级电影" },
    ],
  },

  /* ============ 5. 转场 Transitions ============ */
  {
    key: "transition",
    cn: "过场转场",
    en: "Transitions",
    icon: "✂️",
    tags: [
      { id: "cut", cn: "硬切", en: "Hard Cut",
        prompt: "hard cut transition, instant frame change, abrupt edit",
        desc: "瞬间切换" },
      { id: "fade_in", cn: "淡入", en: "Fade In",
        prompt: "fade in from black, gradual brightness reveal, scene opening",
        desc: "由黑场渐显" },
      { id: "fade_out", cn: "淡出", en: "Fade Out",
        prompt: "fade out to black, gradual darkness, scene closing",
        desc: "渐入黑场" },
      { id: "dissolve", cn: "叠化", en: "Cross Dissolve",
        prompt: "cross dissolve, two scenes blending overlapping, soft transition, time passage",
        desc: "两画面交叠" },
      { id: "wipe", cn: "划像", en: "Wipe",
        prompt: "wipe transition, one scene pushing another off-screen, geometric edge",
        desc: "推开式切换" },
      { id: "match_cut", cn: "匹配剪辑", en: "Match Cut",
        prompt: "match cut transition, visual or motion continuity between two distinct scenes",
        desc: "形态/动作匹配" },
      { id: "j_cut", cn: "J 切", en: "J-Cut",
        prompt: "J-cut, audio of next scene begins before visual cut, sound bridge",
        desc: "声音先入" },
      { id: "l_cut", cn: "L 切", en: "L-Cut",
        prompt: "L-cut, audio of previous scene continues after visual cut, sound carryover",
        desc: "声音延续" },
      { id: "white_flash", cn: "白闪", en: "White Flash",
        prompt: "white flash transition, bright burst between scenes, impact moment",
        desc: "白光闪过" },
      { id: "black_flash", cn: "黑场闪", en: "Black Flash",
        prompt: "black flash transition, sudden darkness between scenes, dramatic beat",
        desc: "黑光闪过" },
      { id: "iris", cn: "光圈", en: "Iris",
        prompt: "iris transition, circle opening or closing, classic vintage film effect",
        desc: "圆形开合" },
      { id: "smash_cut", cn: "强切", en: "Smash Cut",
        prompt: "smash cut, jarring abrupt edit between contrasting scenes, shocking",
        desc: "对比强烈" },
      { id: "jump_cut", cn: "跳切", en: "Jump Cut",
        prompt: "jump cut, time skip within same scene, discontinuity for energy",
        desc: "同场景跳跃" },
      { id: "morph", cn: "形变", en: "Morph",
        prompt: "morph transition, smooth shape transformation between subjects",
        desc: "形态融合" },
    ],
  },
];

/* ============ 组合模板 Combo Templates ============ */
export const COMBO_TEMPLATES: ComboTemplate[] = [
  {
    id: "opening",
    cn: "史诗开场",
    en: "Epic Opening",
    icon: "🎆",
    desc: "升镜 + 18mm 超广角 + IMAX 史诗感 + 淡入",
    tagIds: ["rise", "crane_up", "18mm", "imax_70", "fade_in"],
  },
  {
    id: "dialogue",
    cn: "对话场景",
    en: "Dialogue Scene",
    icon: "💬",
    desc: "85mm 人像 + 固定镜头 + 叠化 + 柔和肤色",
    tagIds: ["static", "85mm", "canon_c500", "dissolve"],
  },
  {
    id: "chase",
    cn: "追逐戏",
    en: "Chase Scene",
    icon: "🏃",
    desc: "手持 + 跟拍 + 甩镜 + 快切 + 锐利数码",
    tagIds: ["handheld", "follow", "whip", "shake", "smash_cut", "red_raptor"],
  },
  {
    id: "monologue",
    cn: "独白思考",
    en: "Inner Monologue",
    icon: "🧠",
    desc: "推镜 + 50mm + 复古镜头 + L 切",
    tagIds: ["push", "dolly_in", "50mm", "vintage", "l_cut"],
  },
  {
    id: "climax",
    cn: "情绪高潮",
    en: "Emotional Climax",
    icon: "💥",
    desc: "拉镜 + 仰拍 + 变形宽银幕 + 白闪 + ARRI 65",
    tagIds: ["pull", "low_angle", "anamorphic", "white_flash", "alexa_65"],
  },
  {
    id: "revealer",
    cn: "悬念揭示",
    en: "The Reveal",
    icon: "🔍",
    desc: "环绕 + 推镜 + 倾斜角 + 匹配剪辑",
    tagIds: ["orbit", "push", "dutch", "match_cut", "alexa_mini"],
  },
  {
    id: "vlog",
    cn: "Vlog 日常",
    en: "Vlog Daily",
    icon: "📱",
    desc: "第一视角 + 手持 + 35mm + Sony FX6 + J 切",
    tagIds: ["pov", "handheld", "35mm_cine", "sony_fx6", "j_cut"],
  },
  {
    id: "wong_kar_wai",
    cn: "王家卫文艺",
    en: "Wong Kar-wai Style",
    icon: "🌃",
    desc: "手持 + 移镜 + 复古老镜头 + 柯达胶片 + 跳切",
    tagIds: ["handheld", "trolley", "vintage", "kodak_35", "jump_cut"],
  },
  {
    id: "nolan",
    cn: "诺兰史诗",
    en: "Nolan Epic",
    icon: "🌌",
    desc: "升降 + 18mm 广角 + IMAX 70mm + 匹配剪辑",
    tagIds: ["crane_up", "18mm", "imax_70", "match_cut"],
  },
  {
    id: "cyberpunk",
    cn: "赛博朋克",
    en: "Cyberpunk",
    icon: "🤖",
    desc: "变焦推拉 + 仰拍 + 变形宽银幕 + RED 8K + 强切",
    tagIds: ["dolly_zoom", "low_angle", "anamorphic", "red_monstro", "smash_cut"],
  },
  {
    id: "horror",
    cn: "悬疑惊悚",
    en: "Horror/Thriller",
    icon: "👻",
    desc: "倾斜角 + 推镜 + 变焦推拉 + 黑场闪",
    tagIds: ["dutch", "push", "dolly_zoom", "black_flash", "vintage"],
  },
  {
    id: "macro_ad",
    cn: "微距广告",
    en: "Macro Commercial",
    icon: "💎",
    desc: "推镜 + Laowa 探针 + 微距 + ARRI Mini LF",
    tagIds: ["dolly_in", "probe", "macro", "alexa_mini", "dissolve"],
  },
];

/** 把选中的 tag id 拼成 prompt 字符串 */
export function buildTagPrompt(selectedIds: string[]): string {
  const allTags = TAG_LIBRARY.flatMap(c => c.tags);
  const selected = selectedIds
    .map(id => allTags.find(t => t.id === id))
    .filter(Boolean) as PresetTag[];
  if (selected.length === 0) return "";
  return selected.map(t => t.prompt).join(", ");
}
